../testdata/error_in_object_local:1:36-46 Called value must be a function, but it is assumed to be void

{ local foo(bar) = error bar, baz: foo("xxx") }


